### ISSUE TITLE
unsuccessful build

### ISSUE THREAD

**Issue by shadylabs** [mah0x211/lua-aerospike#1]
Tried to make using luarocks make and the supplied rockspec file but no luck so far. many errors from las_util.c.
Ubuntu 14.04 64bit / latest versions of Lua and Aerospike
Need some help building lua-aerospike.
Thanks
Plamen

**Comment by mah0x211** [comment]
I had updated it.
you can make this module with following command;

```
luarocks make
```

and, to do test;

```
./tools/memcheck ./tests/tests.lua
```

above environment is osx. (sorry, i don't have ubuntu environment)

but.., i don't recommend to use this module.
the aerospike-c-library(latest version) have some problems;
the one is it can not used in luajit, and this problem is depended on aerospike-c-library.
aerospike-c-library is statically linked to a lua library. i guess, it was made this issue.
and, a memory related bug.

also, i have no time to developing this module..

but, thanks for sending the issue.

**Comment by shadylabs** [comment]
Thanks a lot. If this is the case with the C lib and LuaJit i have to do big turn. My intentions were to use turbolua and as_lua  to frontend the aerospikedb. I don't like C# / windows server combo. Need to find other way to do the job.
